### ISSUE TITLE
py3 compat tracking

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#1353]
**fix in this before merging #1339**

- [x] gluon/cache.py _a more readable "for key in storage" would be a better pick, and will possible enable leverage future optimization in python_ **py3 incompatibility**
- [ ] contrib/fpdf* _hopefully it's exactly the 1.7.2 as latest stable in its own repo_
- [ ] gluon/contrib/gateways/fcgi.py _those changes IMHO will break something in 2.7 . Given the rise of uwsgi and scgi we should instead rely on the new (and supported) fcgi which in turn depends on flup. A fat warning stating that users relying on fcgi would need flup (which for python/fastcgi hosters is ALWAYS included) would seal the deal_
- [x] gluon/contrib/login_methods/ldap_auth.py _"if type(allowed_groups) != type(list()):" got translated to "if not isinstance(allowed_groups, type(list()))" . Should instead be "if not isinstance(allowed_groups, list)"_
- [ ] gluon/contrib/login_methods/x509_auth.py _won't work with py3, another method is needed_
- [ ] gluon/tools.py : _again, m2crypto is not available for py3_
- [ ] gluon/contrib/shell.py _smells funny, but this would be the 312098312 time we say web shell should not be used. Next release would probably be a REEEEEEALLY good time to drop from the admin app and let the contrib module with a big "won't ever FIX"_
- [ ] gluon/contrib/websocket_messaging.py _won't certainly break 2.7, but I'm not sure it can be considered py3 safe_
- [ ] gluon/globals.py _given the importance of the module, remember to put those #FIXME for py3 in the "let's discuss" recap (or clarify what is left to be decided)_
- [ ] gluon/highlight.py _nothing breaks 2.7 but cgi.escape should be addressed for 3.x_
- [ ] gluon/languages.py _I'd drop iterkeys() alltogether: it doesn't have any improvement over keys() or just the "dry" "for key in dict" syntax_
- [ ] gluon/recfile.py _it has to do with the initial design concept, nothing will break 2.7 but we should really be concerned about relying on auto-closing the stream (py3 will emits warnings about it)_
- [ ] gluon/shell.py as contrib/shell.py: _to me those replacement are not 1:1 . That being said it's on the doctest part which is by far the least utilized part of shell.py_

**maybe valid, but change in behaviour**
- [ ] IS_LENGTH() ?
- [ ] _uwsgi/fgci, nowadays is it visible to support only the former?_ don't think so. But I'd NOT go for altering the included fcgi.py to make it work py3 compatible, rather I'd document a flup requirement and alter fcgi.py accordingly just before releasing the first stable with py3 "advertised" compatibility
- [ ] here and there: _"from gluon" instead of "from .gluon": cheating circular imports or forgot to rewrite ?_

**curiosity**
- [ ] adding current.response.static_version = None on test_router : did some behaviour change ?

**things to remember 1st, AFTER merging this but BEFORE new stable**
- [ ] DAL routine tests should be fixed
- [ ] IS_IP* validators could use the ipaddress library (mostly because it's included in 3 and there is an official backport for 2.7) instead of ipaddr-py from google
- [ ] on the CHANGELOG should also be reported as the very first warning that web2py DOES NOT SUPPORT ANYTHING BUT 2.7 (i.e. not only we don't officially support 2.6 but also
we introduced changes that will surely break running on 2.6)
- [ ] We may consider adding a CHANGELOG entry for brave users to test 3.5 and report back findings

** things to remember 2nd, AFTER merging this but BEFORE advertising py3 support **
- [ ] aes.py @leonelcamara has a solution already
- [ ] cache.disk on win was cited by @leonelcamara, although it seems fixed already
- [ ] utf8.py dependency

**Comment by BuhtigithuB** [comment]
Can we test somehow the resulting w2p build before merging? I mean, since
not only Paolo has contribute to the PR can we dowload a working build of
web2py implementing all the current changes?

**Comment by niphlod** [comment]
the PR is continously built at each commit @ilvalle adds.

**Comment by BuhtigithuB** [comment]
Understand that... How can I don't load a snapshot of current changes and
try the resulting web2py?

**Comment by niphlod** [comment]
the PR originates from a branch stated at the very top (	ilvalle  wants to merge 24 commits into web2py:master from ilvalle:py3_fixes). You go to https://github.com/ilvalle/web2py/tree/py3_fixes and there you have the current status.

**Comment by BuhtigithuB** [comment]
Thanks!

I wasn't sure...

**Comment by ilvalle** [comment]
Is it worth to squash all commits into one?
Regarding ```current.response.static_version``` the point is that somehow the static_version was populated with "1.2.3" perhaps due the fact I changed the tests order?

**Comment by BuhtigithuB** [comment]
Got this trace back when I try to edit file with the online IDE...
Error ticket for "admin"Ticket ID

127.0.0.1.2016-06-07.20-41-37.67989863-e626-4de9-b424-0fc9e8779753
<type 'exceptions.TypeError'> 'module' object is not callableVersion
web2py™ Version 2.14.6-stable+timestamp.2016.05.09.19.18.48Traceback

1.
2.
3.
4.
5.
6.
7.
8.
9.
10.
11.
12.

Traceback (most recent call last):
  File "/home/w2p-py3-fixes/web2py/gluon/restricted.py", line 224, in restricted
    exec(ccode, environment)
  File "/home/w2p-py3-fixes/web2py/applications/admin/controllers/default.py",
line 2000, in <module>
  File "/home/w2p-py3-fixes/web2py/gluon/globals.py", line 404, in <lambda>
    self._caller = lambda f: f()
  File "/home/w2p-py3-fixes/web2py/applications/admin/controllers/default.py",
line 833, in edit
    return response.json(file_details)
  File "/home/w2p-py3-fixes/web2py/gluon/globals.py", line 649, in json
    return json(data, default=default or custom_json)
TypeError: 'module' object is not callable

**Comment by BuhtigithuB** [comment]
I also would like to be brave, but I got this :

python3.5 web2py.py
Traceback (most recent call last):
  File
"/home/noitulove/PycharmProjects/w2p-py3-fixes/web2py/gluon/utils.py", line
34, in <module>
    from Crypto.Cipher import AES
ImportError: No module named 'Crypto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "web2py.py", line 21, in <module>
    import gluon.widget
  File
"/home/noitulove/PycharmProjects/w2p-py3-fixes/web2py/gluon/__init__.py",
line 32, in <module>
    from .globals import current
  File
"/home/noitulove/PycharmProjects/w2p-py3-fixes/web2py/gluon/globals.py",
line 20, in <module>
    from gluon.html import xmlescape, TABLE, TR, PRE, URL
  File
"/home/noitulove/PycharmProjects/w2p-py3-fixes/web2py/gluon/html.py", line
28, in <module>
    from gluon.utils import web2py_uuid, simple_hash, compare
  File
"/home/noitulove/PycharmProjects/w2p-py3-fixes/web2py/gluon/utils.py", line
36, in <module>
    import gluon.contrib.aes as AES
  File
"/home/noitulove/PycharmProjects/w2p-py3-fixes/web2py/gluon/contrib/aes.py",
line 440, in <module>
    '637c777bf26b6fc53001672bfed7ab76'
AttributeError: 'str' object has no attribute 'decode'


I know that issue had been discussed...

Why first Simone proposal for pycrypto (
https://pypi.python.org/pypi/pycrypto) won't work exactly?

Thanks

Richard

**Comment by BuhtigithuB** [comment]
I run system test and got this :

testSoap (gluon.tests.test_web.TestWeb) ...
ERROR:gluon.contrib.pysimplesoap.server:Traceback (most recent call last):
  File "/home/w2p-py3-fixes/web2py/gluon/contrib/pysimplesoap/server.py",
line 184, in dispatch
    ret = function(**args)
  File
"/home/w2p-py3-fixes/web2py/applications/examples/controllers/soap_examples.py",
line 26, in division
    return a / b
ZeroDivisionError: float division by zero

ERROR:gluon.contrib.pysimplesoap.server:Traceback (most recent call last):
  File "/home/w2p-py3-fixes/web2py/gluon/contrib/pysimplesoap/server.py",
line 184, in dispatch
    ret = function(**args)
  File
"/home/w2p-py3-fixes/web2py/applications/examples/controllers/soap_examples.py",
line 26, in division
    return a / b
ZeroDivisionError: float division by zero


AND

This :
ERROR: testRetryFailed (gluon.tests.test_scheduler.TestsForSchedulerRunner)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "gluon/tests/test_scheduler.py", line 484, in testRetryFailed
    ("scheduler_run records are FAILED", (task_run[0].status ==
task_run[1].status == 'FAILED')),
  File "/home/w2p-py3-fixes/web2py/gluon/packages/dal/pydal/objects.py",
line 2544, in __getitem__
    row = self.records[i]
IndexError: list index out of range

**Comment by ilvalle** [comment]
@BuhtigithuB try to install ```pycrypto```. Regarding the json error, I need to double check why is raising this error. I remember web2py has unitests for ```json()```, perhaps an other test is neeed

**Comment by niphlod** [comment]
IMHO the json problem is to blame for another commit, which probably obliterated response.json().
It has already been reported here https://github.com/web2py/web2py/issues/1337, and is probably due to fixes @leonelcamara pushed altering json

**Comment by niphlod** [comment]
@BuhtigithuB : once again, the last time you already complained about it and complained also when I told you those simplesoap errors are EXPECTED (and tests pass). You can be brave but crying wolf doesn't help anyone.

**Comment by BuhtigithuB** [comment]
@niphlod, sorry if I already report that... I am in and out... Just try to help.

**Comment by BuhtigithuB** [comment]
@ilvalle, pycrypto is there, it seems to improve things a bit, but I fall on this : 

> python3.5 web2py.py 
Traceback (most recent call last):
  File "web2py.py", line 18, in <module>
    import gluon.widget
  File "/home/w2p-py3-fixes/web2py_w2p_py3_fixes/gluon/__init__.py", line 32, in <module>
    from globals import current
ImportError: No module named 'globals'

**Comment by BuhtigithuB** [comment]
Fix it then : 

>python3.5 web2py.py
Traceback (most recent call last):
  File "web2py.py", line 18, in <module>
    import gluon.widget
  File "/home/w2p-py3-fixes/web2py_w2p_py3_fixes/gluon/__init__.py", line 32, in <module>
    from gluon.globals import current
  File "/home/w2p-py3-fixes/web2py_w2p_py3_fixes/gluon/globals.py", line 360
    except TypeError, e:
                    ^
SyntaxError: invalid syntax

**Comment by BuhtigithuB** [comment]
Fix it then : 

>python3.5 web2py.py
Traceback (most recent call last):
  File "web2py.py", line 18, in <module>
    import gluon.widget
  File "/home/w2p-py3-fixes/web2py_w2p_py3_fixes/gluon/__init__.py", line 32, in <module>
    from gluon.globals import current
  File "/home/w2p-py3-fixes/web2py_w2p_py3_fixes/gluon/globals.py", line 17, in <module>
    from gluon.storage import Storage, List
  File "/home/w2p-py3-fixes/web2py_w2p_py3_fixes/gluon/storage.py", line 19, in <module>
    import copy_reg
ImportError: No module named 'copy_reg'


I also try to fix with gluon.copy_reg, but no luck... search of location of copy_reg...

**Comment by BuhtigithuB** [comment]
https://docs.python.org/2/library/copy_reg.html

Rename copyreg in py3...

Missing dependency...

**Comment by BuhtigithuB** [comment]
But maybe we should leave these further improvement to a next PR where we focus on make w2p works under 3.5?

**Comment by ilvalle** [comment]
@BuhtigithuB I conform that the json issue wasn't introduced by the PR.
I can't reproduce the other errors you posted. I guest you are working with a wrong branch.

**Comment by BuhtigithuB** [comment]
Hmm... Effectively I am on master of your repo, sorry about false report (I
did delete my setup of yesterday and I start fresh this morning without be
sufficient cautious I guess)...

:)

**Comment by BuhtigithuB** [comment]
git clone -b py3_fixes https://github.com/ilvalle/web2py.git py3_fixes

**Comment by BuhtigithuB** [comment]
Better, it start then : 

>python3.5 web2py.py                                                                                                                                                                   
Warning: web2py requires Python 2.7 but you are running:
3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330]ERROR:root:New installation error: unable to create welcome.w2p file
web2py Web Framework
Created by Massimo Di Pierro, Copyright 2007-2016
Version 2.14.6-stable+timestamp.2016.05.09.19.18.48
Database drivers available: pg8000, sqlite3, imaplib
WARNING:web2py:GUI not available because Tk library is not installed
choose a password:

please visit:
        http://127.0.0.1:8000/
use "kill -SIGTERM 13518" to shutdown the web2py server


ERROR:Rocket.Errors.Thread-2:Traceback (most recent call last):

  File "/home/w2p-py3-fixes/web2py_py3_fixes/gluon/rocket.py", line 1339, in run
    self.run_app(conn)

  File "/home/w2p-py3-fixes/web2py_py3_fixes/gluon/rocket.py", line 1840, in run_app
    output = self.app(environ, self.start_response)

  File "/home/w2p-py3-fixes/web2py_py3_fixes/gluon/main.py", line 645, in app_with_logging
    ret[0] = wsgiapp(environ, responder2)

  File "/home/w2p-py3-fixes/web2py_py3_fixes/gluon/main.py", line 554, in wsgibase
    http_response, request, environ, ticket)

UnboundLocalError: local variable 'http_response' referenced before assignment

ERROR:Rocket.Errors.Thread-3:Traceback (most recent call last):

  File "/home/w2p-py3-fixes/web2py_py3_fixes/gluon/rocket.py", line 1339, in run
    self.run_app(conn)

  File "/home/w2p-py3-fixes/web2py_py3_fixes/gluon/rocket.py", line 1840, in run_app
    output = self.app(environ, self.start_response)

  File "/home/w2p-py3-fixes/web2py_py3_fixes/gluon/main.py", line 645, in app_with_logging
    ret[0] = wsgiapp(environ, responder2)

  File "/home/w2p-py3-fixes/web2py_py3_fixes/gluon/main.py", line 554, in wsgibase
    http_response, request, environ, ticket)

UnboundLocalError: local variable 'http_response' referenced before assignment

**Comment by ilvalle** [comment]
Current branch is not py3 ready, there are several things to fix. we agreed in stopping the 'migration' and concentrate the effort to fix any potential py2.7 error introduced. All other issues regarding py3 will be address in a second step.

**Comment by niphlod** [comment]
task tracking updated according to status as reported right now. People, if you fix things, or have additional notes, chime in. I may be slipping some things (the more eyes on this the better)

**Comment by BuhtigithuB** [comment]
Fine will focus on py2.7 for now... Thanks

**Comment by ilvalle** [comment]
- ```globals.py``` has few FIXME
- ```uft8.py``` should be fixed now, 
- ```fcgi.py``` which change is breaking py2?
- ```shell.py``` shall I revert the changes?
- ```"from gluon" instead of "from .gluon"``` for any file inside gluon I used the former. is it visible to drop custom_importer in py3?
- ``` gluon/contrib/websocket_messaging.py``` is not py3 ready yet

**Comment by michele-comitini** [comment]
the x509 login method should not need m2crypto anymore

2016-06-08 22:26 GMT+02:00 ilvalle <notifications@github.com>:

**Comment by BuhtigithuB** [comment]
I try my app under 2.7 and didn't notice much issue so far... I will
execute my tests tomorrow...

Good work!

Richard

**Comment by niphlod** [comment]
> the x509 login method should not need m2crypto anymore

@michele-comitini : meaning you have an alternative in mind or .... we just need to remember ?

**Comment by niphlod** [comment]
> globals.py has few FIXME

   ok. anything pertinent to 2.7 breaking ? if so, should be discussed. If pertinent only to py3, let's put on the "let's remember"
> uft8.py should be fixed now,

   marked as done
> fcgi.py which change is breaking py2?

long to int. I'm not THAT worried about, but that thing isn't nearly py3 "proofed" as the fgci adapter from "official" repo uses flup (which IS py3 compat AND battle tested). From the POV of py3 compat, we should adopt the new one. At the point of this commit "readying the stage for py3", those mods should be discarded.
> shell.py shall I revert the changes?

dunno. @mdipierro ?
> "from gluon" instead of "from .gluon" for any file inside gluon I used the former. is it visible to drop custom_importer in py3?

don't think so. custom_importer is what makes application portable independently of the name it has (with lots of quirks around, but still, it's a pretty consolidated "way of working")
> gluon/contrib/websocket_messaging.py is not py3 ready yet

   marked

**Comment by ilvalle** [comment]
I updated the PR, reverting changes in ```fcgi.py``` e removing iterkeys() in ```languages.py```.
Yes, the ''FIXME'' messages in ```globals.py``` regard only py3.

**Comment by niphlod** [comment]
okay, updated as of now. 
We miss just a decision about gluon/shell.py "replacements".
I'm going to check if this merge would swallow the latest PR merged and get back here.

**Comment by niphlod** [comment]
it seems it SHOULD not swallow, but some of the files have been touched. git merge is intelligent and wonderful but nonetheless I added a task to make sure .

**Comment by michele-comitini** [comment]
@niphlod just a reminder to myself
Since ssl module of 2.7 should support better x509 certificate handling...
Should since I did not test it...

Il giovedì 9 giugno 2016, niphlod <notifications@github.com> ha scritto:
> the x509 login method should not need m2crypto anymore
>
> @michele-comitini : meaning you have an alternative in mind or .... we
just need to remember ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/d7Qp03GJKRECjOylR3AzB1iOf-HsysgJ9VJqsgOeL8VilcSdhkHDBGcgQTOXnjEMM3rYsfbSFJmwNFYrG2uoH4QNMVs-KxcpKRcGs8CmGkyn4FGGgfV09GaIztKNH8MlDQ0vB_7KMg1Ag1REtWossqLv5_ECKA=s0-d-e1-ft#https://github.com/notifications/beacon/ABL7XNLqJ3SNG8CkHfMqunjXUz6ogIXCks5qJ9M4gaJpZM4IwTLO.gif
>

**Comment by ilvalle** [comment]
+1 for dropping shell in future releases.

**Comment by niphlod** [comment]
@ilvalle : we can surely drop the web shell from admin and not touch contrib/shell.py but not gluon/shell.py : that is vital.

**Comment by ilvalle** [comment]
Ok, so if @mdipierro agree in dropping it, I can revert my changes. Otherwise, which changes do you think are breaking py2.7 in ```contrib/shell.py``` ?

**Comment by niphlod** [comment]
lines 401 and 412. 
As already said, it's in the doctest part and I don't know what it's doing in the first place with those lines (read, they may be well dropped alltogether for what I care about) but passing from

    thing in (types.TypeType, types.ClassType)
to

    thing in (type)

just CAN'T be unharmful.

**Comment by ilvalle** [comment]
I've updated both ```shell.py``` to fix ```types.ClassType```. ```types.TypeType``` in py27 is an alias for ```type``` as a result it is ok

**Comment by niphlod** [comment]
ok, updated as of today.

**Comment by ilvalle** [comment]
DAL tests are fixed in https://github.com/web2py/web2py/pull/1361 
utf8.py seems to work with the recent fixes

**Comment by niphlod** [comment]
updated again, pruning a bit of comments on this "thread"

**Comment by mdipierro** [comment]
Ok with everything. Will not be able to review chages to shell.py until
tonight.

**Comment by mdipierro** [comment]
Ps will be in italy next week with lot more time for this.

**Comment by niphlod** [comment]
@mdipierro : shell was merged already .  
PS: bring an umbrella (ot three). Weather is not Italy's best suit right now :-P

**Comment by ilvalle** [comment]
@mdipierro beside shell, have a look at test_is_url too

**Comment by ilvalle** [comment]
I've seen that the coverage reports are not including py3 run, I'd add this to the TODO list.
Is it worth to introduce tox as in pydal?

**Comment by niphlod** [comment]
@ilvalle: it's the last point. Also, what tox brings ?

**Comment by ilvalle** [comment]
I don't know tox that much, I thought it could be used to better define py3 deps.

**Comment by ilvalle** [comment]
@niphlod is https://pypi.python.org/pypi/ipaddress the one you mention?

**Comment by BuhtigithuB** [comment]
I think it was this : https://docs.python.org/3/library/ipaddress.html

But what you found if allow to use the same syntax could help
transitionning...

**Comment by ilvalle** [comment]
@BuhtigithuB that one is only for py3. I'm looking for the port to py2, I'm not sure it's the one I posted.

**Comment by BuhtigithuB** [comment]
Understand what you want... I think you found a good prospect as long as
the syntax is the same as the one of py3 ipaddress... So we can write tests
once and execute them in py2.7 and py3...

**Comment by niphlod** [comment]
@ilvalle : in the long run I think we SHOULD have deps but in the short-medium one, at least until web2py is succesfully packaged, it will remain a "it works unzipping it" framework.

**Comment by ilvalle** [comment]
The checklist can be updated:
- #1361 has been merged.
- _"from gluon" instead of "from .gluon"_ at the moment it works well on both py2 and py3
- IS_LENGTH, on py3 returns the input as is without encoding it.
@leonelcamara have you checked if cache.disk is working on win?

In current master almost all unittests are enable against PY3, only test_scheduler and test_is_url are missing.

**Comment by niphlod** [comment]
ok, I think I updated all the relevant bits

BTW: I'll have some time to spend on the scheduler on the weekend

**Comment by ilvalle** [comment]
@niphlod have you tried scheduler on py3?
A few checkboxes can be marked as done in the first post.

**Comment by niphlod** [comment]
I'm slowingly progressing but ATM no major issues popped up (sadly, no major ideas to have a better way to test it have come up, too). 
BTW: checked what was to be checked, feel free to pinpoint something I'm missing (or something to add)

**Comment by ilvalle** [comment]
web2pyDialog needs to be ported, would you add a point?

**Comment by niphlod** [comment]
done

**Comment by niphlod** [comment]
@web2py/team-web2py : should we start using github projects for this (and possible other scenarios, like the trello board ?? )

**Comment by niphlod** [comment]
meaning ... use github projects INSTEAD of the trello board, which for whatever reason didn't get traction ?

**Comment by gi0baro** [comment]
@niphlod I suggest overv.io ;)

**Comment by niphlod** [comment]
@gi0baro, I'd be +n for it (or waffle, or lots of similar tools) but sadly everything out of the main repo gets rapidly discarded

**Comment by ilvalle** [comment]
A few broken functions for admin app:
- debug (perhaps related to https://github.com/web2py/web2py/issues/1471)
- wizard step6
- update_languages
- appadmin/ccache

**Comment by niphlod** [comment]
Ok, added

**Comment by niphlod** [comment]
made some pruning, too, to keep this issue short

**Comment by ilvalle** [comment]
@niphlod you can update the first post with the fixes made in https://github.com/web2py/web2py/pull/1499

**Comment by niphlod** [comment]
@ilvalle : done.

**Comment by leonelcamara** [comment]
@ilvalle @niphlod while playing around with my refactor of Auth, I just noticed that if you set settings.email_case_sensitive=False in PY3 what gets stored in the email field is "b'test@example.com'" is there a reason for IS_LOWER (or IS_UPPER)  to be calling to_bytes on the result?

**Comment by leonelcamara** [comment]
I will change it in my branch from to_bytes to to_native which I consider is the more correct approach.

**Comment by ilvalle** [comment]
On py35 almost all validators returns bytes. By doing so, it's more compatible with py27.
However, to some extent I agree with you, for example IS_LENGTH works in that way. 
On py27
 ```
>>> IS_LENGTH(2)(u'°2')
('\xc2\xb02', None)
```
On py35
```
>>> IS_LENGTH(2)(u'°2')
('°2', None)
```
It's an open point to discuss. Surely validators should behave all in the same way.

**Comment by leonelcamara** [comment]
I kind of disagree with validators changing what they get, if they get unicode they should return unicode, if they get bytes then bytes it should be, if they never want bytes and only want to deal with native strings then they should complain about it. The problem here is not only that the IS_LOWER is changing the string to bytes, the problem is that IS_EMAIL then puts the representation of those bytes inside a string "b'test@example.com'" yes that b' is really inside the resulting email from passing the bytes from IS_LOWER to IS_EMAIL.

**Comment by ilvalle** [comment]
I see the problem, would you post a PR for such issue?

> I kind of disagree with validators changing what they get

Mind that this is how web2py works on py27, changing it in py35 will require to adapt unittests.

**Comment by leonelcamara** [comment]
> @ilvalle : are you saying that utf8.py and markmin don't need to be tested ? doctests cover html.py, utf8.py and markmin2hhtml. html.py has a corresponding unittest suite, the other 2 no.

@niphlod PY3 doesn't need utf8.py at all as it doesn't have any of the problems of PY2 since the strings will always be unicode, that will cause it to fail the test when they try to test if repr is different as it won't be. 
html.py was very easy to make pass by changing strings in the doctests to strings prefixed with b e.g.: b'\<div>\</div>' and adding this test_old_doctests.py:

    class Py23DocChecker(doctest.OutputChecker):
        """ This way we can use b'' strings for doctests in PY3 """

        def check_output(self, want, got, optionflags):
            if PY2:
                want = re.sub("b'(.*?)'", "'\\1'", want)
                want = re.sub('b"(.*?)"', '"\\1"', want)
            return doctest.OutputChecker.check_output(self, want, got, optionflags)

    tests.addTests(
        doctest.DocTestSuite('gluon.html', checker=Py23DocChecker())
    )

So this makes html.py pass, then utf8.py I think we can just skip for py3 and really don't use it at all maybe by adding this to languages.py

    if not PY2:
        # Python 3 doesnt't need Utf8
        Utf8 = lambda x: x 

This would need to be really tested to see languages.py works as expected.

As for markmin, it doesn't seem to work for py3 except for very basic things.

     >>> render("**@{probe:t=a}**", environment=dict(probe=lambda t:"test %s" % t, a=1))
    '<p><strong>test 1</strong></p>'

This test doesn't work at all

**Comment by ilvalle** [comment]
@leonelcamara proposal for gluon.html.py is fine to me, markmin needs to be fixed somehow.
Regarding the checklist, @niphlod you can check 'fixme in globals' and add a new line 'FIX contrib.minify'

**Comment by niphlod** [comment]
done, plus pruned a bit older posts

**Comment by BuhtigithuB** [comment]
[ ] fix docstring for python 3 (ex.: print something -> print(something))

**Comment by ilvalle** [comment]
@michele-comitini do you have any update or suggestion regarding x509 login in order to avoid m2crypto?

**Comment by leonelcamara** [comment]
@ilvale maybe we could replace m2crypto with [cryptography](https://github.com/pyca/cryptography) which supports python 2 and 3.

**Comment by henriavelabarbe** [comment]
Hi, I'm trying to setup web2py on python3 with nginx using uwsgi.
Uwsgi logs show that it process all 0 bytes answers from web2py.
From what I see, it's because python3 and web2py return unicode data.
Is there a fast workaround to make web2py and uwsgi works using python 3 ?

**Comment by leonelcamara** [comment]
@henriavelabarbe can you try something for me?  
  
In gluon/http.py on the "from _compat" imports add to_bytes

then on class HTTP method "to" where you see:
    
    else:
        return [str(body)]

replace that with

    else:
        body = str(body)
        if isinstance(body, unicodeT):
            body = to_bytes(body)
        return [body]

Don't forget to restart uwsgi, try it, and let me know if that works
